from pathlib import Path


class SigmaGenerator:

    def __init__(self, output_dir="reports/sigma"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, analysis):

        incident = analysis.get("incident", "Unknown")
        severity = analysis.get("severity", "LOW")
        source_ip = analysis.get("source_ip", "0.0.0.0")

        file_name = (
            incident.lower()
            .replace(" ", "_")
            .replace("/", "_")
            + ".yml"
        )

        file_path = self.output_dir / file_name

        sigma_rule = f"""title: {incident}
id: autogenerated-{incident.lower().replace(" ", "-")}
status: experimental
description: Automatically generated Sigma rule by CyberLog AI
author: CyberLog AI
date: 2026-08-05

logsource:
  product: linux
  service: security

detection:
  selection:
    SourceIp: "{source_ip}"
  condition: selection

level: {severity.lower()}

tags:
  - attack
"""

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(sigma_rule)

        return file_path
