import json
import uuid
from pathlib import Path
from datetime import datetime


class STIXExporter:

    def __init__(self, output_dir="reports/stix"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, analysis):

        incident = analysis.get("incident", "Unknown")
        source_ip = analysis.get("source_ip", "")
        severity = analysis.get("severity", "LOW")

        stix_bundle = {
            "type": "bundle",
            "id": f"bundle--{uuid.uuid4()}",
            "objects": [
                {
                    "type": "indicator",
                    "spec_version": "2.1",
                    "id": f"indicator--{uuid.uuid4()}",
                    "created": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
                    "modified": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
                    "name": incident,
                    "description": "Generated by CyberLog AI",
                    "pattern": f"[ipv4-addr:value = '{source_ip}']",
                    "pattern_type": "stix",
                    "valid_from": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
                    "labels": [
                        severity.lower()
                    ]
                }
            ]
        }

        file_name = (
            incident.lower()
            .replace(" ", "_")
            .replace("/", "_")
            + "_stix.json"
        )

        file_path = self.output_dir / file_name

        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(
                stix_bundle,
                f,
                indent=4,
                ensure_ascii=False
            )

        return file_path
